# Generated by Django 4.1.7 on 2023-03-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgeneration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
    ]
