# Generated by Django 4.1.7 on 2023-03-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgeneration', '0002_pdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
