# Generated by Django 4.1.7 on 2023-03-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgeneration', '0005_document_description_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
